[tool.poetry]
name = "payments-plataform"
version = "0.1.0"
description = "payments platform"
authors = ["pinheiro <mfp186@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
annotated-types = "0.7.0"
anyio = "4.6.0"
async-timeout = "4.0.3"
asyncpg = "0.29.0"
certifi = "2024.8.30"
click = "8.1.7"
dnspython = "2.7.0"
email-validator = "2.2.0"
exceptiongroup = "1.2.2"
fastapi = "0.115.2"
fastapi-cli = "0.0.5"
greenlet = "3.1.1"
h11 = "0.14.0"
httpcore = "1.0.6"
httptools = "0.6.1"
httpx = "0.27.2"
idna = "3.10"
jinja2 = "3.1.4"
markdown-it-py = "3.0.0"
markupsafe = "3.0.1"
mdurl = "0.1.2"
psycopg2-binary = "2.9.9"
pydantic = "2.9.2"
pydantic-settings = "2.5.2"
pydantic-core = "2.23.4"
pygments = "2.18.0"
python-dotenv = "1.0.1"
python-multipart = "0.0.12"
pyyaml = "6.0.2"
rich = "13.9.2"
shellingham = "1.5.4"
sniffio = "1.3.1"
sqlalchemy = "2.0.35"
sqlmodel = "0.0.22"
starlette = "0.39.2"
typer = "0.12.5"
typing-extensions = "4.12.2"
uvicorn = "0.31.1"
uvloop = "0.20.0"
watchfiles = "0.24.0"
websockets = "13.1"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
