"""Alterando nome da coluna de identidade

Revision ID: 556a05e4f5ee
Revises: 5a8014549265
Create Date: 2024-12-22 07:05:39.873462

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '556a05e4f5ee'
down_revision: Union[str, None] = '5a8014549265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name="_user",
        column_name="registro_nacional",
        new_column_name="identity_number"
    )
    op.drop_constraint('_user_registro_nacional_key', '_user', type_='unique')
    op.create_unique_constraint('uc_user_identity_number', '_user', ['identity_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name="_user",
        column_name="identity_number",
        new_column_name="registro_nacional"
    )
    op.drop_constraint('uc_user_identity_number', '_user', type_='unique')
    op.create_unique_constraint('_user_registro_nacional_key', '_user', ['registro_nacional'])
    # ### end Alembic commands ###
