"""Refactor transaction model

Revision ID: 5a8014549265
Revises: f739205ae2e9
Create Date: 2024-12-04 16:47:43.630062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8014549265'
down_revision: Union[str, None] = 'f739205ae2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # create custom types
    op.execute("CREATE TYPE transaction_type AS ENUM (\'DEPOSIT\', \'WITHDRAWAL\', \'TRANSFER\')")
    op.execute("CREATE TYPE transaction_status AS ENUM (\'PENDING\', \'COMPLETED\', \'FAILED\', \'REVERSED\')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('transaction', sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='transaction_status'), nullable=False))
    op.add_column('transaction', sa.Column('sender_wallet_id', sa.Uuid(), nullable=False))
    op.add_column('transaction', sa.Column('recipient_wallet_id', sa.Uuid(), nullable=False))
    op.add_column('transaction', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.execute('''
        ALTER TABLE transaction
        ALTER COLUMN type TYPE transaction_type
        USING type::text::transaction_type
    ''')
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    op.drop_constraint('transaction_wallet_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'wallet', ['sender_wallet_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'wallet', ['recipient_wallet_id'], ['id'])
    op.drop_column('transaction', 'value')
    op.drop_column('transaction', 'wallet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('wallet_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('transaction', sa.Column('value', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_wallet_id_fkey', 'transaction', 'wallet', ['wallet_id'], ['id'])
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.alter_column('transaction', 'type',
               existing_type=sa.Enum('DEPOSIT', 'WITHDRAWAL', 'TRANSFER', name='transactiontype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('transaction', 'timestamp')
    op.drop_column('transaction', 'recipient_wallet_id')
    op.drop_column('transaction', 'sender_wallet_id')
    op.drop_column('transaction', 'status')
    op.drop_column('transaction', 'amount')
    # ### end Alembic commands ###
    # drop custom types
    op.execute("DROP TYPE transaction_type")
    op.execute("DROP TYPE transaction_status")
