"""Adicionando status na tabela _user

Revision ID: f739205ae2e9
Revises: 00658f8e30ea
Create Date: 2024-11-29 16:28:30.657417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f739205ae2e9'
down_revision: Union[str, None] = '00658f8e30ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('_user', sa.Column('status', sa.Boolean(), server_default=sa.true(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('_user', 'status')
    # ### end Alembic commands ###
